version: '3.8'

services:

#   object_detection:
#     build: ./object_detection
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db
#       - kafka
#       - schema-registry
    db:
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        ACCEPT_EULA: 'Y'
        MSSQL_SA_PASSWORD_FILE: /run/secrets/SA_PASSWORD
      volumes:
        - E:/security_camera/data:/var/opt/mssql/data
        - E:/security_camera/logs:/var/opt/mssql/log
      secrets:
        - SA_PASSWORD
      ports:
        - "1433:1433"
        
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
      volumes:
        - E:/security_camera/data/zookeeper:/data
        - E:/security_camera/logs/zookeeper:/datalog

    kafka:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - E:/security_camera/data/kafka:/kafka
        - E:/security_camera/logs/kafka:/var/log/kafka
      depends_on:
        - zookeeper
    


secrets:
  SA_PASSWORD:
    file: ./secrets/SA_PASSWORD
  example:
    file: ./secrets/.env
