version: '3'

services:
    security_camera:
        build: ./camera
        volumes: 
            - E:/security_camera/data:/opt/build/data
            - E:/security_camera/logs:/opt/build/logs
        secrets:
            - example
        environment:
            - sleeptime=5
            - camera_url=rtsp://admin:@192.168.50.30:554/h264Preview_01_main
            - camera_name=testcamera
        ports:
          - "5000:5000"
        networks:
          - security_camera_network
secrets:
    example:
        file: ./secrets/example

networks:
  security_camera_network:
