# Dockerfile for object detection

# Use a base image
FROM python:3.11.1-slim-buster

# Set the working directory
WORKDIR /app

# Install the required packages
# RUN pip install -r requirements.txt
RUN pip install dataclasses
RUN pip install kafka-python
RUN pip install avro-python3
RUN pip install numpy
RUN pip install 'transformers[torch]'
RUN pip install Pillow
RUN pip install torch

# Copy the requirements file
COPY requirements.txt .


# Copy the source code
COPY app.py .
COPY ObjectDetectionResult.avsc .
COPY log_config.py .
COPY logging.yaml .

# List installed packages for debug
RUN pip freeze logs/requirements.txt_generated

# Set the entrypoint command
CMD ["python", "app.py"]
