# Dockerfile for object detection

# Use a base image
FROM python:3.9-slim-buster

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code
COPY app.py .
COPY ObjectDetectionResult.avsc .
COPY log_config.py .
COPY logging.yaml .

# Set the entrypoint command
CMD ["python", "app.py"]
