FROM python:3.8

# Install dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install fastapi uvicorn opencv-python-headless tensorflow==2.6.0

# load model into data folder
RUN mkdir /app/data
COPY ./yolov5s.pt /app/data/yolov5s.pt

# Copy code
COPY . /app
WORKDIR /app

# Expose ports
EXPOSE 8000

# Set entrypoint
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]