version: '3'
services:
    sighthound_monitor:
        build: ./
        volumes: 
            - E:/test:/archive
            - E:/sighthound_patch/logs:/logs
        secrets:
            - destination_email
            - login
            - password
        environment:
            - sleeptime=60
            - image_count=1
        #restart: unless-stopped
secrets:
    destination_email:
        file: ./secrets/destination_email
    login:
        file: ./secrets/login
    password:
        file: ./secrets/password